[package]
name = "day_03"
version = "0.1.0"
authors = ["Miguel Molina <miguel@erizocosmi.co>"]

[[bin]]
name = "03"
path = "src/03.rs"

[[bin]]
name = "03b"
path = "src/03b.rs"

[dependencies]
regex = "1.1.0"
lazy_static = "1.2.0"
itertools = "0.7.11"
