[package]
name = "day_10"
version = "0.1.0"
authors = ["Miguel Molina <miguel@erizocosmi.co>"]

[[bin]]
name = "10"
path = "src/10.rs"

[[bin]]
name = "10b"
path = "src/10b.rs"

[dependencies]
regex = "1.1.0"
lazy_static = "1.2.0"
